(cl:defpackage beginner_msgsrv-srv
  (:use )
  (:export
   "ADDTWOINT"
   "<ADDTWOINT-REQUEST>"
   "ADDTWOINT-REQUEST"
   "<ADDTWOINT-RESPONSE>"
   "ADDTWOINT-RESPONSE"
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
  ))

