// Generated by gencpp from file beginner_msgsrv/AddTwoInts.msg
// DO NOT EDIT!


#ifndef BEGINNER_MSGSRV_MESSAGE_ADDTWOINTS_H
#define BEGINNER_MSGSRV_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <beginner_msgsrv/AddTwoIntsRequest.h>
#include <beginner_msgsrv/AddTwoIntsResponse.h>


namespace beginner_msgsrv
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace beginner_msgsrv


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_msgsrv::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::beginner_msgsrv::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::beginner_msgsrv::AddTwoInts > {
  static const char* value()
  {
    return "beginner_msgsrv/AddTwoInts";
  }

  static const char* value(const ::beginner_msgsrv::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_msgsrv::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::beginner_msgsrv::AddTwoInts > 
template<>
struct MD5Sum< ::beginner_msgsrv::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_msgsrv::AddTwoInts >::value();
  }
  static const char* value(const ::beginner_msgsrv::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_msgsrv::AddTwoIntsRequest> should match 
// service_traits::DataType< ::beginner_msgsrv::AddTwoInts > 
template<>
struct DataType< ::beginner_msgsrv::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_msgsrv::AddTwoInts >::value();
  }
  static const char* value(const ::beginner_msgsrv::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_msgsrv::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::beginner_msgsrv::AddTwoInts > 
template<>
struct MD5Sum< ::beginner_msgsrv::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_msgsrv::AddTwoInts >::value();
  }
  static const char* value(const ::beginner_msgsrv::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_msgsrv::AddTwoIntsResponse> should match 
// service_traits::DataType< ::beginner_msgsrv::AddTwoInts > 
template<>
struct DataType< ::beginner_msgsrv::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_msgsrv::AddTwoInts >::value();
  }
  static const char* value(const ::beginner_msgsrv::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_MSGSRV_MESSAGE_ADDTWOINTS_H
